# Generated by Django 5.2.15 on 2026-06-27 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_contactinformation_globalpresence_homepage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['display_order', 'name']},
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='seo_description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='seo_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='seo_description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='homepage',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='homepage',
            name='seo_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='service',
            name='detailed_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='website/services/'),
        ),
        migrations.AddField(
            model_name='service',
            name='outcomes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='process',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='seo_description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='service',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='service',
            name='seo_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.CreateModel(
            name='HomePageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('overview', 'Overview'), ('service_highlight', 'Service Highlight'), ('stat', 'Stat'), ('testimonial', 'Testimonial'), ('call_to_action', 'Call to Action'), ('custom', 'Custom')], default='custom', max_length=40)),
                ('eyebrow', models.CharField(blank=True, max_length=120)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='website/home/sections/')),
                ('link_label', models.CharField(blank=True, max_length=100)),
                ('link_url', models.CharField(blank=True, max_length=250)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('home_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='website.homepage')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
