# Generated by Django 5.2.15 on 2026-06-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_contactenquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Optional structured content: image, benefits, whyChoose, ctaHref, etc.', null=True),
        ),
    ]
