# Generated by Django 6.0.2 on 2026-06-26 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('summary', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='insights/')),
                ('category', models.CharField(choices=[('politics', 'Politics'), ('economy', 'Economy'), ('security', 'Security'), ('human_rights', 'Human Rights'), ('global_trends', 'Global Trends')], default='global_trends', max_length=40)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
