# Generated by Django 6.0.6 on 2026-06-26 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insight',
            name='author_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='insight',
            name='read_time_minutes',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='insight',
            name='tags',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
