# Generated by Django 6.0.6 on 2026-06-26 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0002_insight_author_name_insight_read_time_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insight',
            name='external_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='insight',
            name='raw_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insight',
            name='source_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='insight',
            name='source_url',
            field=models.URLField(blank=True),
        ),
    ]
