# Generated by Django 5.2.15 on 2026-06-27 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0003_insight_external_id_insight_raw_payload_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsightAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='insights/authors/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InsightCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Insight categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InsightTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='insight',
            name='moderation_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='insight',
            name='moderation_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('approved', 'Approved'), ('published', 'Published'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='draft', max_length=30),
        ),
        migrations.AddField(
            model_name='insight',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insights', to='insights.insightauthor'),
        ),
        migrations.AddField(
            model_name='insight',
            name='category_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insights', to='insights.insightcategory'),
        ),
        migrations.CreateModel(
            name='ExternalInsightSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('provider', models.CharField(choices=[('rss', 'RSS'), ('newsapi', 'NewsAPI'), ('gnews', 'GNews')], default='rss', max_length=30)),
                ('endpoint_url', models.URLField()),
                ('api_key_env', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('default_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_sources', to='insights.insightcategory')),
                ('default_tags', models.ManyToManyField(blank=True, to='insights.insighttag')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='insight',
            name='tag_refs',
            field=models.ManyToManyField(blank=True, related_name='insights', to='insights.insighttag'),
        ),
    ]
