# Generated by Django 5.2.15 on 2026-06-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0004_insightauthor_insightcategory_insighttag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insight',
            name='featured_image_url',
            field=models.URLField(blank=True),
        ),
    ]
