# Generated by Django 5.2.15 on 2026-06-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0005_jobapplication_notes_jobapplication_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('reviewing', 'Reviewing'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('hired', 'Hired')], default='submitted', max_length=30),
        ),
    ]
