# Generated by Django 5.2.15 on 2026-06-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0007_applicationstatushistory_recruitmentnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalJobSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('provider', models.CharField(choices=[('greenhouse', 'Greenhouse'), ('lever', 'Lever'), ('workable', 'Workable'), ('ashby', 'Ashby'), ('adzuna', 'Adzuna'), ('jooble', 'Jooble'), ('remoteok', 'Remote OK'), ('custom_json', 'Custom JSON')], default='custom_json', max_length=30)),
                ('endpoint_url', models.URLField()),
                ('api_key_env', models.CharField(blank=True, max_length=100)),
                ('api_secret_env', models.CharField(blank=True, max_length=100)),
                ('default_location', models.CharField(blank=True, max_length=200)),
                ('default_employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('remote', 'Remote')], default='full_time', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
