# Generated by Django 5.2.15 on 2026-06-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0008_externaljobsource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externaljobsource',
            name='provider',
            field=models.CharField(choices=[('greenhouse', 'Greenhouse'), ('lever', 'Lever'), ('workable', 'Workable'), ('ashby', 'Ashby'), ('adzuna', 'Adzuna'), ('jooble', 'Jooble'), ('remoteok', 'Remote OK'), ('myjobmag', 'MyJobMag'), ('custom_json', 'Custom JSON')], default='custom_json', max_length=30),
        ),
    ]
